import type { Meta, StoryObj } from '@storybook/react';
import { Progress } from './Progress';
declare const meta: Meta<typeof Progress>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const Sizes: Story;
export declare const Variants: Story;
export declare const WithLabels: Story;
export declare const Striped: Story;
export declare const Indeterminate: Story;
export declare const Interactive: Story;
export declare const Circular: Story;
export declare const CircularVariants: Story;
export declare const CircularWithCustomLabel: Story;
export declare const CircularIndeterminate: Story;
export declare const MultiStep: Story;
export declare const MultiStepWithNumbers: Story;
export declare const FileUpload: Story;
export declare const Dashboard: Story;
//# sourceMappingURL=Progress.stories.d.ts.map