import type { Meta, StoryObj } from '@storybook/react';
import { Table } from './Table';
declare const meta: Meta<typeof Table>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const Variants: Story;
export declare const Sizes: Story;
export declare const WithSelection: Story;
export declare const Sortable: Story;
export declare const Loading: Story;
export declare const Empty: Story;
export declare const CustomEmptyState: Story;
export declare const WithActions: Story;
export declare const StickyHeader: Story;
export declare const ClickableRows: Story;
export declare const CustomColumnWidth: Story;
export declare const WithFooter: Story;
export declare const ComplexExample: Story;
//# sourceMappingURL=Table.stories.d.ts.map