import type { IconName } from '@bricks/core';
export interface ModuleDefinition {
  id: string;
  pageId: string;
  title: string;
  description: string;
  category: string;
  icon: IconName;
  components: string[];
  source: string;
  wide?: boolean;
}
export const moduleCatalog: ModuleDefinition[] = [
  {
    id: 'analytics',
    pageId: 'DOI-M-ANALYTICS',
    title: '매출 분석',
    description: '기간별 매출과 주요 지표를 함께 살펴보세요.',
    category: '대시보드',
    icon: 'chart-line',
    components: ['Stat', 'Chart', 'Select', 'Badge'],
    source: 'AnalyticsModule.tsx',
    wide: true,
  },
  {
    id: 'projects',
    pageId: 'DOI-M-PROJECTS',
    title: '프로젝트 체크리스트',
    description: '작은 작업을 완료하며 출시를 준비하세요.',
    category: '업무 관리',
    icon: 'circle-check',
    components: ['Checkbox', 'Progress', 'Avatar', 'Badge', 'Button'],
    source: 'ProjectsModule.tsx',
  },
  {
    id: 'team',
    pageId: 'DOI-M-TEAM',
    title: '팀 관리',
    description: '함께 일할 동료를 초대하고 역할을 관리하세요.',
    category: '업무 관리',
    icon: 'users',
    components: ['List', 'Avatar', 'Badge', 'Modal', 'Fieldset', 'Input', 'Select', 'Alert', 'Button'],
    source: 'TeamModule.tsx',
  },
  {
    id: 'orders',
    pageId: 'DOI-M-ORDERS',
    title: '주문 목록',
    description: '주문을 검색하고 처리 상태별로 확인하세요.',
    category: '업무 관리',
    icon: 'receipt',
    components: ['Table', 'Badge', 'Input', 'Select', 'Pagination'],
    source: 'OrdersModule.tsx',
  },
  {
    id: 'onboarding',
    pageId: 'DOI-M-ONBOARDING',
    title: '워크스페이스 시작하기',
    description: '세 단계를 따라 나만의 작업 공간을 구성하세요.',
    category: '폼 & 설정',
    icon: 'sparkles',
    components: ['Steps', 'Fieldset', 'Input', 'Radio', 'Alert', 'Button'],
    source: 'OnboardingModule.tsx',
  },
  {
    id: 'profile',
    pageId: 'DOI-M-PROFILE',
    title: '내 프로필',
    description: '프로필 사진과 동료에게 보여줄 정보를 편집하세요.',
    category: '폼 & 설정',
    icon: 'user-round',
    components: ['Avatar', 'FileInput', 'Fieldset', 'Input', 'Alert', 'Button'],
    source: 'ProfileModule.tsx',
  },
  {
    id: 'notifications',
    pageId: 'DOI-M-NOTIFICATIONS',
    title: '알림 설정',
    description: '필요한 소식을 원하는 방식으로 받아보세요.',
    category: '폼 & 설정',
    icon: 'bell',
    components: ['Toggle', 'Select', 'Fieldset', 'Alert', 'Button'],
    source: 'NotificationsModule.tsx',
  },
  {
    id: 'storage',
    pageId: 'DOI-M-STORAGE',
    title: '파일 보관함',
    description: '파일을 추가하고 저장 공간을 확인하세요.',
    category: '대시보드',
    icon: 'folder',
    components: ['RadialProgress', 'FileInput', 'List', 'Badge', 'Alert', 'Button'],
    source: 'StorageModule.tsx',
  },
  {
    id: 'kanban',
    pageId: 'DOI-M-KANBAN',
    title: '칸반 보드',
    description: '작업을 추가하고 진행 상태별로 정리하세요.',
    category: '업무 관리',
    icon: 'columns-3',
    components: ['Card', 'Input', 'Button', 'Select', 'Avatar', 'Badge', 'ContextMenu'],
    source: 'KanbanModule.tsx',
    wide: true,
  },
  {
    id: 'booking',
    pageId: 'DOI-M-BOOKING',
    title: '일정 예약',
    description: '날짜와 시간, 회의실을 선택하고 예약을 관리하세요.',
    category: '업무 관리',
    icon: 'calendar',
    components: ['DatePicker', 'Fieldset', 'Select', 'Button', 'Badge', 'List', 'Alert'],
    source: 'BookingModule.tsx',
  },
  {
    id: 'billing',
    pageId: 'DOI-M-BILLING',
    title: '요금제 선택',
    description: '월간·연간 요금과 플랜을 비교하고 변경해 보세요.',
    category: '커머스',
    icon: 'credit-card',
    components: ['Card', 'Radio', 'Toggle', 'Badge', 'Button', 'Modal', 'Alert'],
    source: 'BillingModule.tsx',
  },
  {
    id: 'inbox',
    pageId: 'DOI-M-INBOX',
    title: '고객 문의함',
    description: '문의별로 답변하고 대화 영역의 크기를 조절하세요.',
    category: '업무 관리',
    icon: 'messages-square',
    components: ['Card', 'Resizable', 'ChatBubble', 'Avatar', 'Textarea', 'FileInput', 'Button', 'Badge'],
    source: 'InboxModule.tsx',
    wide: true,
  },
  {
    id: 'activity',
    pageId: 'DOI-M-ACTIVITY',
    title: '활동 기록',
    description: '팀의 최근 활동을 확인하고 읽음 상태를 관리하세요.',
    category: '대시보드',
    icon: 'clock',
    components: ['Tabs', 'List', 'Avatar', 'Badge', 'Button'],
    source: 'ActivityModule.tsx',
  },
  {
    id: 'cart',
    pageId: 'DOI-M-CART',
    title: '장바구니',
    description: '상품 수량과 배송비를 확인하고 주문 내용을 검토하세요.',
    category: '커머스',
    icon: 'shopping-bag',
    components: ['List', 'Button', 'Badge', 'Progress', 'Divider', 'Modal', 'Alert'],
    source: 'CartModule.tsx',
  },
];
export const moduleCategories = ['전체', '대시보드', '업무 관리', '폼 & 설정', '커머스'];
