/** Project icon vocabulary: static Lucide imports keep unused icons out of the bundle. */
import {
  Smile,
  Accessibility,
  AppWindow,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  ArrowUpRight,
  Atom,
  Badge,
  Banknote,
  Bell,
  Blocks,
  Book,
  BookOpen,
  Bookmark,
  Box,
  Calendar,
  Camera,
  ChartColumn,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  CircleCheck,
  CircleCheckBig,
  CircleDot,
  CircleHelp,
  CircleUserRound,
  CircleX,
  Clock,
  CloudUpload,
  CodeXml,
  Columns3,
  Command,
  Compass,
  Contact,
  Copy,
  CreditCard,
  Download,
  Ellipsis,
  EllipsisVertical,
  Expand,
  ExternalLink,
  Eye,
  File,
  Flag,
  Folder,
  FolderOpen,
  Globe,
  Grid2X2,
  HardDrive,
  Heading,
  Heart,
  House,
  Image,
  ImagePlus,
  Info,
  Layers,
  LayoutGrid,
  Link,
  List,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  MailCheck,
  Menu,
  MessageCircle,
  MessageSquareMore,
  MessagesSquare,
  Minus,
  Monitor,
  MonitorSmartphone,
  Moon,
  MousePointer2,
  Move,
  Package,
  Palette,
  PanelTop,
  PanelRight,
  PanelsTopLeft,
  Paperclip,
  PenTool,
  Pencil,
  Play,
  Plus,
  Puzzle,
  Receipt,
  RefreshCw,
  Rocket,
  Save,
  Search,
  Send,
  Settings,
  Share2,
  ShoppingBag,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  SquareCheck,
  SquareChevronDown,
  SquareCode,
  Star,
  StickyNote,
  Sun,
  Table,
  TextAlignStart,
  ToggleRight,
  Trash2,
  TriangleAlert,
  Type,
  Upload,
  UserRound,
  UserRoundPlus,
  Users,
  X,
  Zap,
} from 'lucide-react';

export const ICONS = {
  smile: Smile,
  accessibility: Accessibility,
  'app-window': AppWindow,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-down': ArrowUpDown,
  'arrow-up-right': ArrowUpRight,
  atom: Atom,
  badge: Badge,
  banknote: Banknote,
  bell: Bell,
  blocks: Blocks,
  book: Book,
  'book-open': BookOpen,
  bookmark: Bookmark,
  box: Box,
  calendar: Calendar,
  camera: Camera,
  'chart-column': ChartColumn,
  'chart-line': ChartLine,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-down': ChevronsDown,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'circle-check': CircleCheck,
  'circle-check-big': CircleCheckBig,
  'circle-dot': CircleDot,
  'circle-help': CircleHelp,
  'circle-user-round': CircleUserRound,
  'circle-x': CircleX,
  clock: Clock,
  'cloud-upload': CloudUpload,
  'code-xml': CodeXml,
  'columns-3': Columns3,
  command: Command,
  compass: Compass,
  contact: Contact,
  copy: Copy,
  'credit-card': CreditCard,
  download: Download,
  ellipsis: Ellipsis,
  'ellipsis-vertical': EllipsisVertical,
  expand: Expand,
  'external-link': ExternalLink,
  eye: Eye,
  file: File,
  flag: Flag,
  folder: Folder,
  'folder-open': FolderOpen,
  globe: Globe,
  'grid-2x2': Grid2X2,
  'hard-drive': HardDrive,
  heading: Heading,
  heart: Heart,
  house: House,
  image: Image,
  'image-plus': ImagePlus,
  info: Info,
  layers: Layers,
  'layout-grid': LayoutGrid,
  link: Link,
  list: List,
  'loader-circle': LoaderCircle,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  'mail-check': MailCheck,
  menu: Menu,
  'message-circle': MessageCircle,
  'message-square-more': MessageSquareMore,
  'messages-square': MessagesSquare,
  minus: Minus,
  monitor: Monitor,
  'monitor-smartphone': MonitorSmartphone,
  moon: Moon,
  'mouse-pointer-2': MousePointer2,
  move: Move,
  package: Package,
  palette: Palette,
  'panel-top': PanelTop,
  'panel-right': PanelRight,
  'panels-top-left': PanelsTopLeft,
  paperclip: Paperclip,
  'pen-tool': PenTool,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  puzzle: Puzzle,
  receipt: Receipt,
  'refresh-cw': RefreshCw,
  rocket: Rocket,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  'share-2': Share2,
  'shopping-bag': ShoppingBag,
  'sliders-horizontal': SlidersHorizontal,
  smartphone: Smartphone,
  sparkles: Sparkles,
  'square-check': SquareCheck,
  'square-chevron-down': SquareChevronDown,
  'square-code': SquareCode,
  star: Star,
  'sticky-note': StickyNote,
  sun: Sun,
  table: Table,
  'text-align-start': TextAlignStart,
  'toggle-right': ToggleRight,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  type: Type,
  upload: Upload,
  'user-round': UserRound,
  'user-round-plus': UserRoundPlus,
  users: Users,
  x: X,
  zap: Zap,
} as const;
export type IconName = keyof typeof ICONS;
export const ICON_NAMES = Object.keys(ICONS).sort() as IconName[];
