import type { Meta, StoryObj } from '@storybook/react-vite';
import { Avatar } from './Avatar';
declare const meta: Meta<typeof Avatar>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const Sizes: Story;
export declare const Shapes: Story;
export declare const Initials: Story;
export declare const WithStatus: Story;
export declare const Clickable: Story;
export declare const WithBadge: Story;
export declare const CustomContent: Story;
export declare const Loading: Story;
export declare const Fallback: Story;
export declare const Group: Story;
export declare const GroupWithCustomMore: Story;
export declare const UserCards: Story;
export declare const TeamList: Story;
//# sourceMappingURL=Avatar.stories.d.ts.map