import type { Meta, StoryObj } from '@storybook/react-vite';
import { Badge } from './Badge';
declare const meta: Meta<typeof Badge>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const Primary: Story;
export declare const Success: Story;
export declare const Danger: Story;
export declare const Warning: Story;
export declare const Info: Story;
export declare const Rounded: Story;
export declare const Outline: Story;
export declare const Soft: Story;
export declare const Small: Story;
export declare const Large: Story;
export declare const AllSizes: Story;
export declare const TypeComparison: Story;
export declare const WithNumber: Story;
export declare const StatusBadges: Story;
export declare const NotificationBadges: Story;
export declare const AllVariants: Story;
//# sourceMappingURL=Badge.stories.d.ts.map