import type { Meta, StoryObj } from '@storybook/react-vite';
import { Button } from './Button';
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Primary: Story;
export declare const Secondary: Story;
export declare const Success: Story;
export declare const Danger: Story;
export declare const Small: Story;
export declare const Large: Story;
export declare const FullWidth: Story;
export declare const Loading: Story;
export declare const Disabled: Story;
export declare const WithIcon: Story;
export declare const IconOnly: Story;
export declare const Warning: Story;
export declare const Info: Story;
export declare const Light: Story;
export declare const Dark: Story;
export declare const Link: Story;
export declare const Ghost: Story;
export declare const OutlinePrimary: Story;
export declare const OutlineSecondary: Story;
export declare const OutlineSuccess: Story;
export declare const OutlineDanger: Story;
export declare const Pill: Story;
export declare const ExtraSmall: Story;
export declare const ExtraLarge: Story;
export declare const AllVariants: Story;
export declare const AllSizes: Story;
export declare const RoundedVariations: Story;
export declare const ButtonStates: Story;
export declare const ButtonShapes: Story;
//# sourceMappingURL=Button.stories.d.ts.map