import type { Meta, StoryObj } from '@storybook/react-vite';
import { Chart } from './Chart';
declare const meta: Meta<typeof Chart>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const BarChart: Story;
export declare const LineChart: Story;
export declare const AreaChart: Story;
export declare const PieChart: Story;
export declare const DoughnutChart: Story;
export declare const Themes: Story;
export declare const NoGrid: Story;
export declare const NoLegend: Story;
export declare const CustomColors: Story;
export declare const RadarChart: Story;
export declare const PolarChart: Story;
export declare const SmallChart: Story;
export declare const Dashboard: Story;
export declare const Comparison: Story;
export declare const Analytics: Story;
//# sourceMappingURL=Chart.stories.d.ts.map