import type { Meta, StoryObj } from '@storybook/react';
import { Typography } from './Typography';
declare const meta: Meta<typeof Typography>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const Headings: Story;
export declare const DisplayVariants: Story;
export declare const BodyText: Story;
export declare const Colors: Story;
export declare const Weights: Story;
export declare const Alignment: Story;
export declare const TextTransform: Story;
export declare const TextDecoration: Story;
export declare const Truncation: Story;
export declare const Italic: Story;
export declare const InlineDisplay: Story;
export declare const NoSelect: Story;
export declare const CustomElement: Story;
export declare const Article: Story;
export declare const PricingCard: Story;
//# sourceMappingURL=Typography.stories.d.ts.map